export const SCHEMA_STATEMENTS = [
	`CREATE TABLE IF NOT EXISTS hosts (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL,
		region TEXT NOT NULL,
		tier TEXT NOT NULL,
		cpu_total INTEGER NOT NULL,
		memory_mb_total INTEGER NOT NULL,
		storage_gb_total INTEGER NOT NULL,
		min_price REAL NOT NULL,
		max_cpu_pct INTEGER NOT NULL DEFAULT 100,
		ram_cap_mb INTEGER,
		quiet_hours TEXT,
		power_mode TEXT NOT NULL DEFAULT 'balanced',
		daemon_status TEXT NOT NULL DEFAULT 'stopped',
		uptime_7d REAL NOT NULL DEFAULT 95,
		completion_rate REAL NOT NULL DEFAULT 95,
		perf_score REAL NOT NULL DEFAULT 75,
		network_score REAL NOT NULL DEFAULT 75,
		policy_score REAL NOT NULL DEFAULT 90,
		score REAL NOT NULL DEFAULT 0,
		last_heartbeat INTEGER,
		created_at INTEGER NOT NULL,
		updated_at INTEGER NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS pools (
		id TEXT PRIMARY KEY,
		name TEXT NOT NULL UNIQUE,
		is_private INTEGER NOT NULL DEFAULT 1,
		created_at INTEGER NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS pool_members (
		pool_id TEXT NOT NULL,
		host_id TEXT NOT NULL,
		PRIMARY KEY (pool_id, host_id),
		FOREIGN KEY(pool_id) REFERENCES pools(id),
		FOREIGN KEY(host_id) REFERENCES hosts(id)
	);`,
	`CREATE TABLE IF NOT EXISTS workloads (
		id TEXT PRIMARY KEY,
		customer_id TEXT NOT NULL,
		image TEXT NOT NULL,
		cpu INTEGER NOT NULL,
		memory_mb INTEGER NOT NULL,
		storage_gb INTEGER NOT NULL,
		tools TEXT NOT NULL,
		persist_policy TEXT NOT NULL,
		region TEXT NOT NULL,
		tier_required TEXT,
		pool_id TEXT,
		price_cap REAL,
		status TEXT NOT NULL,
		host_id TEXT,
		runtime_id TEXT,
		assigned_rate REAL,
		wake_trigger TEXT,
		created_at INTEGER NOT NULL,
		updated_at INTEGER NOT NULL,
		started_at INTEGER,
		stopped_at INTEGER,
		checkpoint_id TEXT,
		last_error TEXT,
		FOREIGN KEY(host_id) REFERENCES hosts(id)
	);`,
	`CREATE TABLE IF NOT EXISTS assignments (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		workload_id TEXT NOT NULL,
		host_id TEXT NOT NULL,
		action TEXT NOT NULL,
		payload TEXT,
		status TEXT NOT NULL DEFAULT 'pending',
		assigned_at INTEGER NOT NULL,
		handled_at INTEGER,
		reason TEXT,
		FOREIGN KEY(workload_id) REFERENCES workloads(id),
		FOREIGN KEY(host_id) REFERENCES hosts(id)
	);`,
	`CREATE TABLE IF NOT EXISTS usage_events (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		workload_id TEXT NOT NULL,
		host_id TEXT NOT NULL,
		timestamp INTEGER NOT NULL,
		seconds REAL NOT NULL,
		cpu_seconds REAL NOT NULL,
		memory_mb_avg REAL NOT NULL,
		egress_mb REAL NOT NULL DEFAULT 0,
		FOREIGN KEY(workload_id) REFERENCES workloads(id),
		FOREIGN KEY(host_id) REFERENCES hosts(id)
	);`,
	`CREATE TABLE IF NOT EXISTS billing_line_items (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		workload_id TEXT NOT NULL,
		host_id TEXT NOT NULL,
		minute_epoch INTEGER NOT NULL,
		usage_seconds REAL NOT NULL,
		compute_cost REAL NOT NULL,
		storage_cost REAL NOT NULL,
		bandwidth_cost REAL NOT NULL,
		total_cost REAL NOT NULL,
		host_rate REAL NOT NULL,
		platform_take_rate REAL NOT NULL,
		created_at INTEGER NOT NULL,
		UNIQUE(workload_id, minute_epoch)
	);`,
	`CREATE TABLE IF NOT EXISTS host_earnings (
		id INTEGER PRIMARY KEY AUTOINCREMENT,
		host_id TEXT NOT NULL,
		workload_id TEXT NOT NULL,
		minute_epoch INTEGER NOT NULL,
		gross_revenue REAL NOT NULL,
		platform_fee REAL NOT NULL,
		payout REAL NOT NULL,
		created_at INTEGER NOT NULL
	);`,
	`CREATE TABLE IF NOT EXISTS checkpoints (
		id TEXT PRIMARY KEY,
		workload_id TEXT NOT NULL,
		host_id TEXT NOT NULL,
		runtime_reference TEXT,
		metadata TEXT NOT NULL,
		created_at INTEGER NOT NULL,
		FOREIGN KEY(workload_id) REFERENCES workloads(id),
		FOREIGN KEY(host_id) REFERENCES hosts(id)
	);`,
	`CREATE INDEX IF NOT EXISTS idx_workloads_status ON workloads(status);`,
	`CREATE INDEX IF NOT EXISTS idx_workloads_host ON workloads(host_id);`,
	`CREATE INDEX IF NOT EXISTS idx_assignments_host_status ON assignments(host_id, status);`,
	`CREATE INDEX IF NOT EXISTS idx_usage_workload_timestamp ON usage_events(workload_id, timestamp);`,
	`CREATE INDEX IF NOT EXISTS idx_billing_workload_minute ON billing_line_items(workload_id, minute_epoch);`,
]
